feat: 기상청 날씨 API 기능 추가
samdoreee/FieldGeoLogServer pull request #5
Opened 2022-11-10 20:05 UTC by jinyoung-2

## 👀 이슈

resolve #2 

## 📌 개요

기상청 날씨 API 기능

## 👩‍💻 작업 사항

- 기상청 날씨 API를 연동하여 날씨 정보 가져오기 
- 추후에, 위도와 경도를 기상청 X,Y 좌표로 변환하는 코드 추가하기

2022-11-18 07:07 UTC, chisan01 requested changes

2022-11-18 07:07 UTC, chisan01 commented on src/main/java/com/samdoree/fieldgeolog/Spot/Service/WeatherApi.java
> +        String baseDate = "20221110";
기본값 대신 매개변수 값을 사용하도록 변경해주세요~

2022-11-28 13:53 UTC, jinyoung-2 commented on src/main/java/com/samdoree/fieldgeolog/Spot/Service/WeatherApi.java
> +        String baseDate = "20221110";
네! 수정하겠습니다.

2022-12-06 15:15 UTC, chisan01 approved these changes

2022-12-06 15:15 UTC, merged